### ISSUE TITLE
Unify infer/check functions in type checker

### ISSUE THREAD

**Issue by byorgey** [disco-lang/disco#118]
Instead of having separate `infer` and `check` functions, I think it would be nicer to have a single function (`typecheck`?) which takes an extra `Mode` argument, where
```
data Mode where
  Infer :: Mode
  Check :: Type -> Mode
```
One benefit of this approach is that the code for the checking and inference modes for each given syntax node could move right next to each other.  Right now if you want to find e.g. the code for typechecking exponentiation you need to look at two places in the file very far apart --- one in the `infer` definition and one in `check`.  As another benefit, I think there are opportunities for reducing duplicated code, where some constructs can be implemented in a "mode polymorphic" way.

**Comment by SanjitKal** [comment]
Closed by #130.
