### ISSUE TITLE
Add built-in types for graphs

### ISSUE THREAD

**Issue by byorgey** [disco-lang/disco#168]
It would be cool to have built-in support for describing and manipulating graphs.  I'm thinking of something based on [algebraic graphs](https://github.com/snowleopard/alga-paper). Beyond that I haven't put too much thought into it.

**Comment by metadave** [comment]
I'm interested to see how you picture this working in Disco. Maybe start with some code examples and then we can work out the details from there?

**Comment by byorgey** [comment]
* There should be a built-in paramaterized type `Graph v` where `v` is the type of vertex labels. *e.g.* `Graph n` is the type of directed graphs with vertices labeled by natural numbers.
* Internally, graph values should be represented using http://hackage.haskell.org/package/algebraic-graphs-0.5/docs/Algebra-Graph.html#t:Graph .  That is, we should edit the `Value` type (in `Disco.Eval`) and add a new `VGraph` constructor containing an `Algebra.Graph.Graph`.
* We can provide primitive operations `empty : Graph v` and `vertex : v -> Graph v`.
* We can overload `+` and `*` to do the overlay and connect operations, respectively.
    * Briefly, this will require editing `Disco.Types.Rules` to make the `Graph` type satisfy the `QNum` constraint.
    * It will also require changing the compiler to turn `+` and `*` at a `Graph` type into the appropriate primitive graph operations.
* We should make a `graph.disco` file in `lib/` which will export a bunch of these things and where we can add a bunch of other library functions which can be defined on top of the existing primitives.  For example, we could define a function `edge : v -> v -> Graph v` as `edge x y = vertex x * vertex y`.  We should definitely look at the `algebraic-graph` package for ideas of things we can provide.
* As another example, we should provide a primitive function to turn a graph into an adjacency list representation, of type `Graph v -> Set v * Set (v * v)`.  We could also then define `vertices : Graph v -> Set v` and `edges : Graph v -> Set (v * v)` just by projecting out the first or second components of the adjacency list representation.
* As a simple example, here is some code that should hypothetically typecheck:
```
import graph

||| A graph consisting of an isolated vertex and a triangle.
g : Graph N
g = vertex 1 + vertex 2 * edge 3 4

||| The number of edges in the graph `g`. Should be 3.
!!! numEdges == 3
numEdges : N
numEdges = size (edges g)
```

**Comment by byorgey** [comment]
Also, I wonder how we should handle undirected graphs?  We should look more into how the `algebraic-graph` library handles them.

**Comment by byorgey** [comment]
Closed by https://github.com/disco-lang/disco/pull/256 .
