### ISSUE TITLE
Add OEIS interface

### ISSUE THREAD

**Issue by byorgey** [disco-lang/disco#189]
Using the `oeis` package.  Provide some OEIS primitives that allow interaction with the OEIS database.

**Comment by metadave** [comment]
can you provide examples of what this could look like?

**Comment by byorgey** [comment]
Sure!  The [oeis package](hackage.haskell.org/package/oeis) provides a way to retrieve all the info related to a sequence, but I am thinking of keeping things simple.  Maybe we could have two primitives: one to extend a sequence, and the other to yield the URL of a sequence.  So, in more detail:

* Add two new primitives, called something like `lookupSequence` and `extendSequence`.
    * Add them in [`Disco.Syntax.Prims`](https://github.com/disco-lang/disco/blob/master/src/Disco/Syntax/Prims.hs), in both the `Prim` data type and the `primTable`.  Probably make them non-exposed (i.e. set the boolean in the `primTable` to `False`).
    * Add them to [the `inferPrim` function in `Disco.Typecheck`](https://github.com/disco-lang/disco/blob/master/src/Disco/Typecheck.hs#L474).  I'm imagining type `[N] -> String` for `lookupSequence` and `[N] -> [N]` for `extendSequence`.
    * Add corresponding constants to the [`Op` data type in `Disco.AST.Core`](https://github.com/disco-lang/disco/blob/master/src/Disco/AST/Core.hs#L98), and update [the `compilePrim` function in `Disco.Compile`](https://github.com/disco-lang/disco/blob/master/src/Disco/Compile.hs#L120) to trivially turn the new prims into the new `Op` constants.
    * Update [the `whnfOp` function in `Disco.Interpret.Core`](https://github.com/disco-lang/disco/blob/master/src/Disco/Interpret/Core.hs#L804) to handle the new constants.  This is where you would actually write code to call the Haskell `oeis` package and convert back and forth to Disco runtime values.
* Add a new library module `oeis.disco` in `lib/`, and have it simply re-export the prims (you can see how this is done for `num.disco` as an example.
* Add some test cases to the test suite to exercise it.

**Comment by byorgey** [comment]
As a further example of what this might look like when it's working:
```
Disco> import oeis
Disco> :type extendSequence
extendSequence : List ℕ → List ℕ
Disco> extendSequence [0,1,1,2,3,5]
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155]
Disco> :type lookupSequence
lookupSequence : List ℕ → List Char
Disco> lookupSequence [0,1,1,2,3,5]
"http://oeis.org/A000045"
```
I'm also open to other suggestions!
