### ISSUE TITLE
enumerate returns bogus functions

### ISSUE THREAD

**Issue by shaylew** [disco-lang/disco#204]
When you try to enumerate a (finite) function type, you get the right-shaped list but attempts to take out the functions and apply them fail.

```
Disco> map(\f. f True, enumerate (B -> B))
Impossible! funArity on VFun_ <fun>
Disco> enumerate (B -> B) == [\_ . False]
Impossible! funArity on VFun_ <fun>
```

This turns out to be a reasonable complaint, because what `enumerate` gives back is a list of `VFun`s and `VFun`s don't record an arity. It's not reasonable to expect the interpreter to be able to apply the `VFun` without knowing its arity, either.

It turns out that currently `VFun` is only ever used at arity 1, so the simplest thing to do seems to just make that explicit (and turn the list of values it gets as an argument into a single value). But if there's some forward-looking reason to make it more general it's equally easy to add an arity to the constructor.

**Comment by byorgey** [comment]
Huh!  You're totally right.  I'm pretty sure this used to work, back when I added `enumerate`, but I suppose something changed since then and we didn't have a test to catch it.  I think making `VFun` always have arity 1 is reasonable.
