### ISSUE TITLE
Type definitions

### ISSUE THREAD

**Issue by byorgey** [disco-lang/disco#22]
Not sure what the concrete syntax should be, but it would be nice to have a way to declare type synonyms.  For example, something like
```
alias Predicate = N -> Bool

f : Predicate -> Predicate
f p = n -> p (n+1)
```

**Comment by byorgey** [comment]
We can also cheaply encode recursive algebraic data types simply by allowing recursive type definitions.   For example, I imagine this should type check:

```
type NatTree = Unit + N * NatTree * NatTree

treeSum : NatTree -> N
treeSum (left ()) = 0
treeSum (right (x,l,r)) = x + treeSum l + treeSum r
```

A second step would be allowing parameterized type definitions, like  
```
type Tree a = Unit + a * Tree a * Tree a
```
(This would require introducing kinds and kind checking.)

The reason Haskell doesn't allow this --- instead requiring algebraic data types to be declared with constructors --- is because Haskell wants to be able to do complete type inference, and inferring recursive types like this is very difficult (impossible?) without constructor applications to tell you what type is being constructed.  But since disco requires top-level type signatures on everything, this is totally fine.  In other words, we will never be able to *infer* that something has type `NatTree`, but *checking* that something has type `NatTree` should be easy (just keep expanding `NatTree` into its definition whenever necessary).

**Comment by SanjitKal** [comment]
Can this be closed now?

**Comment by byorgey** [comment]
Yes!
