### ISSUE TITLE
:ann command not taking the top-level context into account

### ISSUE THREAD

**Issue by byorgey** [disco-lang/disco#220]
The `:ann` command is supposed to dump a completely type-annotated term after type checking.
```
Disco> import num
Loading num.disco...
Disco> :type factor
factor : ℕ → Bag ℕ
Disco> :ann factor
Unbound factor
```
Probably this is a simple issue of getting the `topCtx` and passing it appropriately when executing the `:ann` command in the REPL.  For comparison, look to see how the `:type` command is processed, since they should work almost identically, differing only in the output produced.

**Comment by metadave** [comment]
Is this the output you're looking for?

```
Disco> :ann factor
TVar_ (TyCon CArr [TyAtom (ABase N),TyCon (CContainer (ABase CtrBag)) [TyAtom (ABase N)]]) factor
```

**Comment by byorgey** [comment]
Yep!
