### ISSUE TITLE
Parse \_. wildcard lambda

### ISSUE THREAD

**Issue by shaylew** [disco-lang/disco#246]
Currently `\_ . true` is accepted, but `\_. true` (without a space after the `_`) results in a parse error.

**Comment by byorgey** [comment]
`parseWild` explicitly says `notFollowedBy ... oneOf opChar`:

https://github.com/disco-lang/disco/blob/master/src/Disco/Parser.hs#L502

But honestly I am not sure why the `oneOf opChar` is there.  Why can't a wildcard be followed immediately by an operator or operator symbol?  Does anything go wrong if we simply remove that `oneOf opChar`?
