### ISSUE TITLE
(List) comprehensions

### ISSUE THREAD

**Issue by byorgey** [disco-lang/disco#30]
Eventually I would like to have list, set, and multiset comprehensions.  Let's start with list comprehensions, similar to [what is in Haskell](https://www.haskell.org/onlinereport/haskell2010/haskellch3.html#x8-420003.11) or Python.  As a start, we can have the Haskell-like syntax (which seems already closest to mathematical practice)
```
'[' e '|' q [',' q]* ']'
```
that is, an expression, followed by a vertical bar, followed by one or more comma-separated *qualifiers* `q`, all enclosed in square brackets.  A qualifier `q` is given by
```
q ::= v 'in' e | e
```
that is, each qualifier `q` is either a variable binding of the form `v in e` for some variable `v` and expression `e`, or an expression `e` by itself (representing a Boolean guard).  Later we can perhaps replace `v` with a pattern, or add `let` qualifiers.

**Comment by callahanhirrel** [comment]
closed by https://github.com/disco-lang/disco/pull/45
