### ISSUE TITLE
Would it make sense to add `iff` as a keyword equivalent to `<->`?

### ISSUE THREAD

**Issue by archonandromeda** [disco-lang/disco#325]
Since the `<->` operator was added with #324 and (most?) other propositional operators have keyword equivalents, having `iff` would make things consistent.

**Comment by byorgey** [comment]
Thanks for the suggestion!  Actually, I did in fact add `iff` as an equivalent to `<->`, in https://github.com/disco-lang/disco/commit/f36970be92bdb24c6295553c607a67eb071bec2d , though I have not yet uploaded a new version with `<->` and `iff` to Hackage.  I will do that soon.
