### ISSUE TITLE
List inference should use lub instead of checking using first type

### ISSUE THREAD

**Issue by byorgey** [disco-lang/disco#33]
```
Disco> [1,2/3]
Mismatch TyN (ATBin TyQP Div (ATNat 2) (ATNat 3))
```
The above ought to have type `List Q+` instead of being a type error.  The problem is that the code to infer the type of a list infers the type of the first element and then checks that all remaining elements have that type.  Instead, we should infer the types of all the elements and compute their least upper bound.

This will require writing a function `lubs :: [Type] -> TCM Type` which works by recursing over the list with `lub`.

As another test, make sure that `[1,-1,2/3]` is inferred to have type `List Q`, since `Q` is the lub of `[N,Z,Q+]`.

**Comment by callahanhirrel** [comment]
Should calling `lubs` on an empty list be an error?

`lubs [] = SomeError`?

**Comment by byorgey** [comment]
Right.  It should be an internal error (i.e. call the `error` function) because it should never happen.  Note that we can't infer the type of an empty list; the `infer` function should only have a case for `infer (TList es@(_:_))` so that it will only match on a non-empty list.  An empty list will fall through to the final "can't infer" case.  So in the case of an empty list it should never call `lubs` at all.
