### ISSUE TITLE
Precedence of juxtaposed multiplication

### ISSUE THREAD

**Issue by byorgey** [disco-lang/disco#4]
```
Disco> let x = 3 in 3x^2
81
```
This should be `3 * 3^2 = 3 * 9 = 27`. The problem is that juxtaposition (`3x`) is parsed with higher precedence than exponentiation, because it might be function application.

We obviously cannot have parsing depend on types.  Perhaps the right solution is to just make function application have lower precedence than exponentiation.  Either way something is going to be strange though.  e.g. what should `f(x)^2` mean?

**Comment by byorgey** [comment]
I am now thinking that making function application have lower precedence than exponentiation may really be the right solution.  That way `3x^2` will parse as `3(x^2)` as you would expect.  So it does mean that `f(x)^2` would parse as `f ((x)^2)`, but honestly I am not too sad about that.  `f(x)^2` may be somewhat standard mathematical notation for `(f(x))^2`, but the fact is that it's kind of ambiguous and confusing anyway.  @callahanhirrel , what do you think?  Would you be tripped up by `f(x)^2` not doing what you expect?  (What would you expect?)

**Comment by callahanhirrel** [comment]
I would expect <f(x)^2> to mean <(f(x))^2>, especially in a "mathematical" context, since <`f(_)`> is always treated like one unit.

That said, if it is the best way to fix juxtaposition, it would be pretty easy to work around exponentiating functions.

**Comment by byorgey** [comment]
Yeah, I think you're right.  After thinking about it some more, I thought of an example which makes the ambiguity all the more stark:
```
y(x-y)^2
f(x-y)^2
```
I think most mathematicians would think of the first as `y * ((x-y)^2)`, and the second as `(f(x-y))^2`.  But the only reason is because of standard conventions about using the letter `f` to stand for functions and the letter `y` to stand for variables, hence the first must be multiplication and the second must be function application.  And in standard mathematical practice, function application has higher precedence than exponentiation, whereas multiplication has lower precedence.

**Comment by byorgey** [comment]
It makes me wonder whether we could have some reasonable *syntactic* way to distinguish between function application and multiplication.  As in, `t1 t2` is multiplication if `t1` "looks like" a multiplicative term (for some suitable definition of "looks like") and function application otherwise.  We could also introduce an explicit function application operator (such as `@`) which could be used if you needed to disambiguate.
