### ISSUE TITLE
Primitive Character type for Unicode code points

### ISSUE THREAD

**Issue by byorgey** [disco-lang/disco#62]
It's not all that mathematical.  But when talking about *e.g.* encryption, or just for general usefulness of writing example programs that can produce messages, it might be nice to have very basic built-in support for handling strings.  Something very basic should be enough:

* A new primitive type `Character` which represents a Unicode codepoint.
* Built-in functions to convert between `Character <-> Integer`; unsure what their names should be.
* Special support for literal strings, which desugar to lists of characters.

There are some issues to be worked out regarding how lists of characters get pretty-printed; see #63.

**Comment by byorgey** [comment]
Or perhaps there should be explicit functions to convert between strings and lists of characters?

**Comment by SanjitKal** [comment]
Character syntax would a single char between two single quotes:
Ex:
Disco> 'c''c'Disco> :type 'c'
` 'c' : Char

String syntax would be a series of chars enclosed by double quotes:
Ex:
Disco> "Hello World"> "Hello World"
Disco> :type "Hello World"> "Hello World" : String

Strings could be represented as a container list of elements of type char. This way, we get to use any operations we define over lists on strings as well.
