### ISSUE TITLE
Add logs for other bases

### ISSUE THREAD

**Issue by byorgey** [disco-lang/disco#80]
For example, right now there is no way to compute the number of decimal digits in a number, since we only have log base 2.  (Note that `lg n / lg 10` does not give the correct result since `lg` rounds down.)

Not sure what the syntax should be.

**Comment by byorgey** [comment]
We don't need special syntax; we can just make a primitive `$log : N * N -> N` and expose it via a library function, probably in `num.disco`.  In fact while we're at it, we can get rid of built-in syntax for `lg` and just define it in the library too, as `$log(2,n)`.

**Comment by ericpinter** [comment]
At the moment it seems like there is a little bit more going on with how `lg` works. An expression like `lg 0` returns a built in error `LgOfZero`. Is it worth keeping this behavior or is a simple `NonExhaustive` enough?

**Comment by byorgey** [comment]
Yes, `NonExhaustive` is more for user-defined functions that encounter a missing case at runtime.  For built-in things like `log` we should have more specific errors when they encounter undefined behavior.
