### ISSUE TITLE
Rounding functions (floor, ceiling, round)

### ISSUE THREAD

**Issue by byorgey** [disco-lang/disco#9]
We should add functions `floor` and `ceiling` for converting from fractional to integral types.  (We might also consider adding a `round` function that rounds to the nearest integer, although it is less obvious what the right semantics is---more on this later.)

Typing rule:
```
Γ ⊢ t ▷ ν
------------
Γ ⊢ floor t ▷ int(ν)
```
where as usual ν denotes any numeric type (use `checkNumTy`), and we define `int(Q+) = int(N) = N` and `int(Q) = int(Z) = Z` (you can add a function to do this).  The typing rule for `ceiling` is the same.

To implement these, you can literally just call the Haskell functions `floor` and `ceiling` on `Rational` values; this produces an `Integer` which you can inject back into the `Rational` type with `% 1`.  These do the right thing even for negative numbers (*e.g.* `floor (-1%2) = -1`, not `0`---`floor` always rounds *down*, not *towards zero*).

Once you get the basic version working it would be fun to actually allow the syntax `⌊x⌋` for `floor x` and `⌈x⌉` for `ceiling x`.  This just requires adding new clauses to `parseAtom` that parse a term in between the appropriate kind of brackets.

The only question with `round` would be what to do with numbers that are exactly halfway between two integers.  Note that the Haskell `round` function actually rounds alternately up and down ("Banker's rounding"):
```
ghci> :m +Data.Ratio
ghci> round (1 % 2)
0
ghci> round (3 % 2)
2
ghci> round (5 % 2)
2
```
and so on.  But I do not think this makes sense for a language with no floating-point type like disco.  It probably makes more sense to define `round` as `round x = floor (x + 1/2)` which means it would always round halves up.  But in that case there is no particular reason to include `round` as a primitive in the language; we can always just define it in terms of `floor` like this.

**Comment by callahanhirrel** [comment]
Closed by https://github.com/disco-lang/disco/pull/26
